apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-nginx-deployment
  labels:
    app: nginx
    stage: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      stage: blue
  template:
    metadata:
      labels:
        app: nginx
        stage: blue
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.14.2
        ports:
        - containerPort: 8080