apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx-deployment
spec:
  #clusterLabels:
  matchLabels:
    cloud: Amazon